import type { Metadata } from "next";
import { montserrat } from "./ui/fonts";
import "./globals.css";
import { Header } from "@/components/widgets";
import { Container } from "@/components/shared/Container";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${montserrat.variable} relative`}>
        <Container className="absolute top-4 left-0 right-0 z-50 px-6">
          <Header />
        </Container>

        {children}
      </body>
    </html>
  );
}
