import type { Metadata } from "next";
import "./globals.css";
import { Header, Footer } from "@/components/widgets";
import { Container } from "@/components/shared/Container";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function LocaleLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { locale: "ru" | "kz" };
}>) {
  const { locale } = await params;
  const messages = await getMessages();

  return (
    <NextIntlClientProvider messages={messages}>
      <Container className="absolute top-4 left-0 right-0 z-50 px-6">
        <Header />
      </Container>
      <main>{children}</main>
      <Container className="bg-gray-100">
        <Footer locale={locale} />
      </Container>
    </NextIntlClientProvider>
  );
}
